<?php
require_once(EPCL_PLUGIN_PATH.'/widgets/about.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/posts-thumbs.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/featured-category.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/related-articles.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/video.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/tweets.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/flickr.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/ads-125.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/ads-fluid.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/social.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/tag-cloud.php');
require_once(EPCL_PLUGIN_PATH.'/widgets/gallery.php');
?>
